PrivateLibrary/Controllers/TakenBookController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PrivateLibrary.Data;
using PrivateLibrary.Data.Models;
using PrivateLibrary.Models.Pagination;
using System.Drawing.Printing;
using static System.Reflection.Metadata.BlobBuilder;

namespace PrivateLibrary.Controllers
{
    public class TakenBookController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TakenBookController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string? search, int pageNumber = 1, int pageSize = 10)
        {
            var takenBooks = _context.TakenBooks.AsQueryable();

            if (!string.IsNullOrEmpty(search))
            {
                ViewBag.Search = search;
                takenBooks = takenBooks.Where(tb => tb.Title.Contains(search) || tb.Author.Contains(search));
            }

            var filtered = await takenBooks
            .Skip((pageNumber - 1) * pageSize)
            .Take(pageSize)
            .ToListAsync();

            var paginatedTakenBooks = new PaginatedList<TakenBook>(filtered, takenBooks.Count(), pageNumber, pageSize);

            return View(paginatedTakenBooks);
        }

        public async Task<IActionResult> Details(int id)
        {
            var takenBook = await _context.TakenBooks
                .Include(tb => tb.Reader)
                .Include(tb => tb.Reader.User)
                .Include(tb => tb.Book)
                .FirstOrDefaultAsync(x => x.Id == id);
            return View(takenBook);
        }

        public async Task<IActionResult> Return(int id)
        {
            var takenBook = await _context.TakenBooks.FirstOrDefaultAsync(x => x.Id == id)
                ?? throw new ArgumentNullException(nameof(id));
            var book = await _context.Books.FirstOrDefaultAsync(x => x.Id == takenBook.BookId)
                ?? throw new ArgumentNullException(nameof(id));

            book.IsTaken = false;
            takenBook.DateOfReturn = DateTime.Now;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index), "Book");
        }
    }
}

PrivateLibrary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrivateLibrary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PrivateLibrary.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PrivateLibrary</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User?.IsInRole("Admin") ?? false)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Employee" asp-action="GetAll">Служители</a>
                            </li>
                        }
                        @if (User?.IsInRole("Admin") ?? false)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Reader" asp-action="GetAll">Читатели</a>
                            </li>
                        }
                        @if (User != null && User.IsInRole("Admin") || User != null && User.IsInRole("Employee"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="TakenBook" asp-action="Index">Всички вземания</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PrivateLibrary - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>